services:
  edvance.database:
    ports:
      - "5432:5432"
  
  edvance.keycloak:
    ports:
      - "8080:8080"
    command: start-dev
    
  edvance.rabbitmq:
    ports:
      - "5672"
      - "15672:15672"
        
  edvance.redis:
    ports:
      - "6379:6379"
        
  edvance.content-service:
    ports:
      - "8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=${POSTGRES_CONNECTION_STRING:-Host=edvance.database;Database=content;Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres}}
      - ConnectionStrings__RedisConnectionString=edvance.redis:6379
      - MessageBroker__Hostname=edvance.rabbitmq
      - MessageBroker__Port=5672
      - MessageBroker__Username=${RABBITMQ_DEFAULT_USER:-guest}
      - MessageBroker__Password=${RABBITMQ_DEFAULT_PASS:-guest}
        
  edvance.api-gateway:
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
