services:
  edvance.database:
    volumes:
      - ./.containers/edvance-db:/var/lib/postgresql/data
  
  edvance.keycloak:
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://edvance.database:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    command: start-dev
